version: '3.9'
services:
  app:
    build:
      context: .
    image: sd-server:local
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
