# run the server in supervisor
# supervisord -c /etc/supervisor/supervisor.conf
# stop the server in supervisor
# supervisorctl -c /etc/supervisor/supervisor.conf stop all

# install the supervisor
# apt-get install -y supervisor

[program:sdif_http_server]
directory=/media/lee/pcd/code/sdif
command=/media/lee/pcd/code/sdif/scripts/run_proteus_server.sh
autostart=true
autorestart=true
environment=HOME="/home/lee",PYTHONPATH="/media/lee/pcd/code/sdif"
stdout_logfile=syslog
stderr_logfile=syslog
